apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
spec:
  endpoints:
    - port: http-metrics
      path: /metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/part-of: redis-failover
      app.kubernetes.io/component: redis
