apiVersion: apps/v1
kind: Deployment
metadata:
  name: alcali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alcali
  template:
    metadata:
      labels:
        app: alcali
    spec:
      containers:
        - name: alcali
          image: latenighttales/alcali:3006.3.0
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: alcali-config
            - secretRef:
                name: alcali-secrets
