apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: salt-master
spec:
  serviceName: "salt-master"
  replicas: 1
  selector:
    matchLabels:
      app: salt-master
  template:
    metadata:
      labels:
        app: salt-master
    spec:
      volumes:
        - name: salt-config-volume
          emptyDir: {}
      initContainers:
        - name: git-clone-salt-config
          image: alpine/git:latest
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/StephenPendrigh/reclaim-the-stack.git
            - /repo
          volumeMounts:
          - name: salt-config-volume
            mountPath: /repo
      containers:
        - name: salt-master
          image: salttake3-master:latest # This is a local image I pushed to k3s by running docker save salttake3-master:latest | sudo k3s ctr images import -
          imagePullPolicy: IfNotPresent
          env:
            - name: PYTHONUNBUFFERED
              value: "true"
          ports:
            - containerPort: 8080
            - containerPort: 4505
            - containerPort: 4506
          volumeMounts:
            - name: salt-config-volume
              subPath: applications/salt-stack/saltconfig/etc/master
              mountPath: /etc/salt/master

            - name: salt-config-volume
              subPath: applications/salt-stack/saltconfig/etc/minion
              mountPath: /etc/salt/minion

            - name: salt-config-volume
              subPath: applications/salt-stack/saltconfig/srv/pillar
              mountPath: /srv/pillar

            - name: salt-config-volume
              subPath: applications/salt-stack/saltconfig/srv/salt
              mountPath: /srv/salt
              
            - name: pki-data
              mountPath: /etc/salt/pki
  volumeClaimTemplates:
    - metadata:
        name: pki-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
