apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - ./namespace.yaml
  - ./tailscale-prom-sidecar-sealedsecret.yaml
  - ./prometheus-rules-cm.yaml
  - ./prometheus-targets-cm.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    # Version upgrade notes and container image versions at:
    # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    # Version changelogs at:
    # https://github.com/prometheus-community/helm-charts/releases
    version: 74.0.0 # operator version 0.83.0 / prometheus version 3.4.1 / grafana version 12.0.1
    namespace: prometheus
    includeCRDs: true
    valuesInline:
      namespaceOverride: "prometheus"
      defaultRules:
        create: false
      kubeApiServer:
        enabled: false
      kubelet:
        enabled: false
      kubeControllerManager:
        enabled: false
      coreDns:
        enabled: false
      kubeEtcd:
        enabled: false
      kubeScheduler:
        enabled: false
      kubeProxy:
        enabled: false
      kube-state-metrics:
        enabled: false
      nodeExporter:
        enabled: false
      prometheus-node-exporter:
        prometheus:
          monitor:
            enabled: false
      grafana:
        enabled: false
      alertmanager:
        enabled: false
      grafana:
        enabled: false
      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 100Mi
          ruleSelector:
            matchLabels:
              prometheus.io/rules: "true"
          alertingEndpoints:
            - name: alertmanager-main
              namespace: alertmanager
              port: 9093
          # Dynamic target scraping
          volumes:
            - name: external-targets
              configMap:
                name: prometheus-external-targets
          volumeMounts:
            - name: external-targets
              mountPath: /etc/prometheus/targets
              readOnly: true
          additionalScrapeConfigs:
            - job_name: 'file-sd-scrape'
              # This tells Prometheus to read targets from our JSON file
              file_sd_configs:
              - files:
                - '/etc/prometheus/targets/external-targets.json'