apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - 
  - prometheus-rules-cm.yaml
  - prometheus-targets-cm.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 58.2.0
    releaseName: prometheus-stack
    namespace: prometheus
    valuesFile: values.yaml