apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - ./namespace.yaml
  - ./tailscale-prom-sidecar-sealedsecret.yaml
  - ./prometheus-rules-cm.yaml
  - ./prometheus-targets-cm.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    # Version upgrade notes and container image versions at:
    # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    # Version changelogs at:
    # https://github.com/prometheus-community/helm-charts/releases
    version: 74.0.0 # operator version 0.83.0 / prometheus version 3.4.1 / grafana version 12.0.1
    namespace: prometheus
    includeCRDs: true
    valuesInline:
      defaultRules:
        create: false
      kubeApiServer:
        enabled: false
      kubelet:
        enabled: false
      kubeControllerManager:
        enabled: false
      coreDns:
        enabled: false
      kubeEtcd:
        enabled: false
      kubeScheduler:
        enabled: false
      kubeProxy:
        enabled: false
      kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        prometheus:
          monitor:
            enabled: false
      grafana:
        enabled: false
      alertmanager:
        enabled: false
      grafana:
        enabled: false
      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 100Mi
          ruleSelector:
            matchLabels:
              prometheus.io/rules: "true"
          podMonitorSelectorNilUsesHelmValues: false
          probeSelectorNilUsesHelmValues: false
          ruleSelectorNilUsesHelmValues: false
          serviceMonitorSelectorNilUsesHelmValues: false