apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-sidecar-secret-access
  namespace: prometheus
rules:
  # Permission to read and write the state secret
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale-prom-sidecard-auth"]
    verbs: ["get", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-tailscale-sidecar-binding
  namespace: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-kube-prometheus-prometheus
    namespace: prometheus
roleRef:
  kind: Role
  name: tailscale-sidecar-secret-access
  apiGroup: rbac.authorization.k8s.io