apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - ./namespace.yaml
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cloudnative-pg
    version: 0.23.2 # CloudnativePG version 1.25.1
    namespace: cnpg-system
    valuesInline:
      monitoring:
        grafanaDashboard:
          create: true
          namespace: monitoring
          sidecarLabelValue: "1"
          forceString: true
        podMonitorEnabled: true
