apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: platform
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    # Chart versions at https://artifacthub.io/packages/helm/stakater/reloader
    # Changelog at https://github.com/stakater/Reloader/releases
    targetRevision: 2.1.3 # app version 1.4.2
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true