apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../applications/shared-secrets/tailscale-oauth-encrypted.yaml
helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.84.2
    releaseName: tailscale-operator
    namespace: tailscale
    valuesFile: values.yaml
