apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - argocd-funnel
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              # The argocd-server service uses port 80 for http
              # and 443 for https. Since the tailscale ingress
              # terminates TLS, we connect to the http port.
              number: 80
