---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAA5ixMdjdu2i8NTZr/kH001tVv8Ae2D8XX8iShjt7Xqi0WsnXhXeVd45xXMp91htsqYcYezhtyuFXpYusPUIzSV13T4mY8oaGTyTwSmOTSz9X0dYe7h27556P7I1U+Kaz+LfjWEsLpYaRe1v+s9fog9gD/AM7itI6Qm6HLMOGdWYj6cvG6y9eNmySZ5r7Ij1gq3vQqL6YW96tJSBgUUerpeKWkfNgKoKmbTv3A7nmVGSUV8L2DqyxP01EMLxtJWy7IAnqxoZvGt/sfMkBbRRPHK5Cnkqv3ZwnviOou1VUvFvRRSGGlhfG9hD8fo4kwDfpQY2uOX6jGz0ynnt2ySjUtruRQ40b8ly1UqvUwkTecGGnhG5Cq4cNqidTUfMZC8mvE9g6FnJJGJ8V1me6BGlddLvuMNqRpWyaf7jvFMQmW2iKP5KaCKAJOgvfDdKMIFNE/8LlsPOOmBe8ZWgcLjSHIe8Epia0XVBI9z7+6BdWQMVoC7NM3IvxeJhkYrgbm1DP9vz/hncqA9K3Yb3wdcnhg3K67VCJxfVW7S/tXoN2XESuE0UrCk5tbCWdU8U4CSeOvvOOUUy5dwzbdOVQybTaCp/B85YNLDblLg+1wUiKyJW3sO69i5q/DPRLagn3ViDba+Cm0Fc0rdctpY22Q8aJR9bsIXZCacUgq5y0+v/Aiql8zT3FxtWDP7Mws9CgA2v+IQqOXAqeKkhB7EhPTn/VcqA==
    client_secret: AgBSXiGmwAXzwky+XXLF5Kw9P3kQZs1X0NQ/+lNEbzmFwKQ4PyJJQmRKo1SHEHF8eFKJSG6QXWfVmmNmABJ8MWlcWZ8qBwDgbFxg8iRTDY6tFBVrXaIWpuCQjvYMfk+ENxOqwjB4bSaRL9dPn3kKX7WFYd63BIp6nI5tTPtfs2trvlZ1nFw/rfHyttXHezbnHngBOQjt6frqIZxLrAZe6Rqdw9JvAh0nKdHi3BysflK9+n7GvGLmLI8nijRG2U4Co6MISmHGwHgNLQNOanWdgRMTMdtA6wvDpZLTnnX/6JnFredGUgAjjV4pQUWpmXMnEBOrsrHmzDhMnN0i6RHHZ4XAjGacTVkDXwFupAaeQtWgs/swDBOKtM97cr7o8kBdH+5dZ672D16VqXrgs2kfLkQg0C4Fbu7viVcAtXGpzoG22MtZxhbczSNUdKwVClR0luyrnip+XRhQtC7JDA4ct4yTi9d2w/iZhTg/cI5Kye/yQdQp+2Qf0mYV0P3jm0yaEvgHIlCSXQptnAeoeoKjO4orki3fDqBrwRKw7BIXHj9HijTXABtJBQyBwK/c1vVGQCY7fUMRSTDxrZs/WCCmM9f9oa9xlWisimsbTvt2Z5CLXA/r7l7U5dwjkyVIFv+r7O/2Y3uOwOdxn8a82nSaG8o7hjUn8UOQUeqmf0RAaaSxI0CCf65hCd+rEU/BjT9AaXnEn0y0XqwQeYNc+2D4VWaPqRVVScyAYAcM93nWAQjDoGfr+EN8mCRhjOh+6VYYJz+LUFLig16TcRvjOEv8WeM=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-oauth
      namespace: tailscale
    type: Opaque
